version: "3.9"

services:
  app:
    container_name: docker_laravel_react_app
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./src/:/app

  nginx:
    container_name: docker_laravel_react_nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 8082:80
    depends_on:
      - app
    volumes:
      - ./src/:/app

  mysql:
    container_name: docker_laravel_react_mysql
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql-volume:/var/lib/mysql
      
volumes:
  mysql-volume:
